[features]
seeds = false
skip-lint = false
[programs.localnet]
octav3 = "DPVWSd9QHuwfwipPM3HyPdpxq5zzvLXF1yHnX4aoK3cd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "node tests/octav3.js"
