[features]
seeds = false
skip-lint = false
[programs.devnet]
adv_nft="3yvqsncdr3Ua1kiXEWZ9iwFqRjnAEe3DdDiZvpzabJ9D"
music_nft="5EiC52YiZEUpxh678MVyi36QBj8GFqfuqLGHsxSdGvaN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
