[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "DPVWSd9QHuwfwipPM3HyPdpxq5zzvLXF1yHnX4aoK3cd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
