[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "2CKBt8szyDwSY2bvYYRaLUkqrnLjAW5fcPnkWbXBx8ge"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
